services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports: ["27017:27017"]
    volumes: ["mongo1_data:/data/db"]
    networks: [appnet]

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports: ["27018:27017"]
    volumes: ["mongo2_data:/data/db"]
    networks: [appnet]

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports: ["27019:27017"]
    volumes: ["mongo3_data:/data/db"]
    networks: [appnet]

  mongors-init:
    image: mongo:7
    container_name: mongors-init
    depends_on: [mongo1, mongo2, mongo3]
    networks: [appnet]
    entrypoint: >
      bash -lc "
      sleep 5 &&
      mongosh --host mongo1:27017 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo1:27017\" },
            { _id: 1, host: \"mongo2:27017\" },
            { _id: 2, host: \"mongo3:27017\" }
          ]
        })
      '"

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - neo4j_data:/data
    networks: [appnet]

  redis:
    image: redis:7
    container_name: redis
    ports: ["6379:6379"]
    networks: [appnet]

  backend:
    build: ./backend
    container_name: backend
    ports: ["3000:3000"]
    depends_on: [mongors-init, neo4j, redis]
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/research?replicaSet=rs0
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=password123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks: [appnet]

networks:
  appnet:

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  neo4j_data:
